"""added table

Revision ID: 7c98928e8f05
Revises: dbdd5fc4f5f6
Create Date: 2023-12-14 17:41:28.577679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c98928e8f05'
down_revision: Union[str, None] = 'dbdd5fc4f5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('garage', sa.String(), nullable=True),
    sa.Column('balconyNumber', sa.Integer(), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('door', sa.String(), nullable=True),
    sa.Column('window', sa.String(), nullable=True),
    sa.Column('floor', sa.String(), nullable=True),
    sa.Column('windowNumber', sa.Integer(), nullable=True),
    sa.Column('buildingFloor', sa.Integer(), nullable=True),
    sa.Column('whichFloor', sa.Integer(), nullable=True),
    sa.Column('commissionYear', sa.Integer(), nullable=True),
    sa.Column('leasing', sa.String(), nullable=True),
    sa.Column('progress', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('province', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('propertyType', sa.String(), nullable=True),
    sa.Column('sellType', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('img_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property_images')
    op.drop_table('properties')
    # ### end Alembic commands ###
