"""added khoroo column

Revision ID: 8aeda29dd793
Revises: 7c98928e8f05
Create Date: 2023-12-15 15:59:11.140954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aeda29dd793'
down_revision: Union[str, None] = '7c98928e8f05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('khoroo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'khoroo')
    # ### end Alembic commands ###
